# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
asJSONNumeric <- function(x, digits = 3L, precision = 0L) {
    .Call('rspeed_asJSONNumeric', PACKAGE = 'rspeed', x, digits, precision)
}

escape_one <- function(x) {
    .Call('rspeed_escape_one', PACKAGE = 'rspeed', x)
}

#' @export
escape_chars_cpp <- function(x) {
    .Call('rspeed_escape_chars_cpp', PACKAGE = 'rspeed', x)
}

